packages:
  - "apps/*"
  - "packages/*"

minimumReleaseAge: 1440
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 525600
blockExoticSubdeps: true
strictDepBuilds: true
allowBuilds:
  argon2: true
  electron: true
  electron-winstaller: false
  esbuild: true
  msgpackr-extract: false
  onnxruntime-node: true
  protobufjs: false
  sharp: true
