server {
  listen 8080;

  location ^~ /internal/ {
    return 404;
  }

  location / {
    proxy_pass http://koed-server:3300;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}
