CREATE TABLE "projection_policy_rules" (
	"source_kind" text DEFAULT 'codex' NOT NULL,
	"source_adapter_version" text DEFAULT 'codex-transcript-v1' NOT NULL,
	"transcript_type" text NOT NULL,
	"description" text,
	"project_to_ui" boolean DEFAULT false NOT NULL,
	"create_message" boolean DEFAULT false NOT NULL,
	"create_tool_event" boolean DEFAULT false NOT NULL,
	"create_memory_event" boolean DEFAULT false NOT NULL,
	"include_in_embedding" boolean DEFAULT false NOT NULL,
	"include_in_lcm" boolean DEFAULT false NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "projection_policy_rules_source_kind_source_adapter_version_transcript_type_pk" PRIMARY KEY("source_kind","source_adapter_version","transcript_type"),
	CONSTRAINT "projection_policy_rules_message_ui_check" CHECK ("projection_policy_rules"."create_message" = false or "projection_policy_rules"."project_to_ui" = true),
	CONSTRAINT "projection_policy_rules_tool_ui_check" CHECK ("projection_policy_rules"."create_tool_event" = false or "projection_policy_rules"."project_to_ui" = true),
	CONSTRAINT "projection_policy_rules_embedding_memory_check" CHECK ("projection_policy_rules"."include_in_embedding" = false or "projection_policy_rules"."create_memory_event" = true),
	CONSTRAINT "projection_policy_rules_lcm_memory_check" CHECK ("projection_policy_rules"."include_in_lcm" = false or "projection_policy_rules"."create_memory_event" = true)
);
--> statement-breakpoint
ALTER TABLE "messages" ADD COLUMN "source_event_time" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "tool_events" ADD COLUMN "source_event_time" timestamp with time zone;--> statement-breakpoint
UPDATE "messages" SET "source_event_time" = "captured_at" WHERE "source_event_time" IS NULL;--> statement-breakpoint
UPDATE "tool_events" SET "source_event_time" = "captured_at" WHERE "source_event_time" IS NULL;--> statement-breakpoint
CREATE INDEX "projection_policy_rules_lookup_idx" ON "projection_policy_rules" USING btree ("source_kind","source_adapter_version","transcript_type","enabled");--> statement-breakpoint
INSERT INTO "projection_policy_rules" (
	"transcript_type",
	"description",
	"project_to_ui",
	"create_message",
	"create_tool_event",
	"create_memory_event",
	"include_in_embedding",
	"include_in_lcm"
) VALUES
	('user_message', 'User-authored transcript message.', true, true, false, true, true, true),
	('assistant_message', 'Assistant-authored transcript message.', true, true, false, true, true, true),
	('agent_message', 'Agent-authored transcript message.', true, true, false, true, true, true),
	('subagent_message', 'Subagent-authored transcript message.', true, true, false, true, true, true),
	('message', 'Role-bearing transcript message item.', true, true, false, true, true, true),
	('function_call', 'Transcript tool/function call.', true, true, true, true, true, true),
	('function_call_output', 'Transcript tool/function result.', true, true, true, true, true, true),
	('custom_tool_call', 'Transcript custom tool call.', true, true, true, true, true, true),
	('custom_tool_call_output', 'Transcript custom tool result.', true, true, true, true, true, true),
	('tool_call', 'Normalized transcript tool call.', true, true, true, true, true, true),
	('tool_result', 'Normalized transcript tool result.', true, true, true, true, true, true),
	('codex_tool_result', 'Legacy normalized Codex tool result label.', true, true, true, true, true, true),
	('codex_transcript_user', 'Legacy normalized Codex user transcript label.', true, true, false, true, true, true),
	('codex_transcript_agent', 'Legacy normalized Codex agent transcript label.', true, true, false, true, true, true),
	('codex_transcript_subagent', 'Legacy normalized Codex subagent transcript label.', true, true, false, true, true, true),
	('codex_transcript_tool', 'Legacy normalized Codex tool transcript label.', true, true, true, true, true, true),
	('reasoning_summary', 'Model reasoning summary safe for display and embedding.', true, true, false, true, true, true),
	('summary_reasoning', 'Model reasoning summary safe for display and embedding.', true, true, false, true, true, true),
	('thought_summary', 'Model thought summary safe for display and embedding.', true, true, false, true, true, true),
	('summary_thought', 'Model thought summary safe for display and embedding.', true, true, false, true, true, true),
	('reasoning', 'Non-raw reasoning summary item.', true, true, false, true, true, true),
	('thought', 'Non-raw thought summary item.', true, true, false, true, true, true),
	('ide_context', 'IDE/supporting context retained as raw provenance only.', false, false, false, false, false, false),
	('client_context', 'Client context retained as raw provenance only.', false, false, false, false, false, false),
	('additional_context', 'Additional context retained as raw provenance only.', false, false, false, false, false, false),
	('application_context', 'Application context retained as raw provenance only.', false, false, false, false, false, false),
	('system', 'System context retained as raw provenance only.', false, false, false, false, false, false),
	('system_message', 'System message retained as raw provenance only.', false, false, false, false, false, false),
	('developer', 'Developer context retained as raw provenance only.', false, false, false, false, false, false),
	('developer_message', 'Developer message retained as raw provenance only.', false, false, false, false, false, false),
	('instruction', 'Instruction context retained as raw provenance only.', false, false, false, false, false, false),
	('rolling_context', 'Rolling context retained as raw provenance only.', false, false, false, false, false, false),
	('context_summary', 'Context summary retained as raw provenance only.', false, false, false, false, false, false),
	('session_meta', 'Session metadata retained as raw provenance only.', false, false, false, false, false, false),
	('lifecycle', 'Lifecycle event retained as raw provenance only.', false, false, false, false, false, false),
	('initialized', 'Initialization event retained as raw provenance only.', false, false, false, false, false, false),
	('task_started', 'Task lifecycle event retained as raw provenance only.', false, false, false, false, false, false),
	('task_complete', 'Task lifecycle event retained as raw provenance only.', false, false, false, false, false, false),
	('turn/completed', 'Turn-completed control event retained as raw provenance only.', false, false, false, false, false, false),
	('turn_context', 'Turn context retained as raw provenance only.', false, false, false, false, false, false),
	('context_compacted', 'Context compaction event retained as raw provenance only.', false, false, false, false, false, false),
	('compacted', 'Compacted transcript replacement retained as raw provenance only.', false, false, false, false, false, false),
	('thread/tokenusage/updated', 'Token usage telemetry retained outside semantic memory.', false, false, false, false, false, false),
	('tokenusage', 'Token usage telemetry retained outside semantic memory.', false, false, false, false, false, false),
	('token_count', 'Token-count telemetry retained outside semantic memory.', false, false, false, false, false, false),
	('mcp_tool_call_start', 'Low-level MCP tool lifecycle event retained as raw provenance only.', false, false, false, false, false, false),
	('mcp_tool_call_end', 'Low-level MCP tool lifecycle event retained as raw provenance only.', false, false, false, false, false, false),
	('patch_apply_start', 'Low-level patch lifecycle event retained as raw provenance only.', false, false, false, false, false, false),
	('patch_apply_end', 'Low-level patch lifecycle event retained as raw provenance only.', false, false, false, false, false, false),
	('error', 'Error telemetry retained as raw provenance only.', false, false, false, false, false, false),
	('agentmessage/delta', 'Incremental agent delta retained as raw provenance only.', false, false, false, false, false, false),
	('reasoning_raw', 'Raw reasoning content is never projected.', false, false, false, false, false, false),
	('raw_reasoning', 'Raw reasoning content is never projected.', false, false, false, false, false, false),
	('raw_content', 'Raw content fragment is never projected.', false, false, false, false, false, false),
	('reasoning_raw_content', 'Raw reasoning content is never projected.', false, false, false, false, false, false),
	('reasoning_text_delta', 'Raw reasoning delta is never projected.', false, false, false, false, false, false),
	('reasoning_raw_content_delta', 'Raw reasoning delta is never projected.', false, false, false, false, false, false),
	('reasoningtextdelta', 'Raw reasoning delta is never projected.', false, false, false, false, false, false),
	('reasoningrawcontent', 'Raw reasoning content is never projected.', false, false, false, false, false, false),
	('reasoningrawcontentdelta', 'Raw reasoning delta is never projected.', false, false, false, false, false, false),
	('unknown', 'Unknown transcript items are retained as raw provenance only.', false, false, false, false, false, false);
