import {
  PINNED_PRIVACY_ARTIFACT_SHA256,
  PINNED_PRIVACY_CALIBRATION_SHA256,
  PINNED_PRIVACY_CLASSIFIER_HASH,
  PINNED_PRIVACY_DECODER_SHA256,
  PINNED_PRIVACY_DETERMINISTIC_DETECTOR_VERSION,
  PINNED_PRIVACY_MODEL_ID,
  PINNED_PRIVACY_MODEL_REVISION,
  PINNED_PRIVACY_Q4_DATA_SHA256,
  PINNED_PRIVACY_Q4_DATA_SIZE,
  PINNED_PRIVACY_Q4_ONNX_SHA256,
  PINNED_PRIVACY_Q4_ONNX_SIZE,
  PINNED_PRIVACY_TOKENIZER_SHA256
} from "@koed/shared";

export const OFFICIAL_PRIVACY_MODEL_ID = PINNED_PRIVACY_MODEL_ID;
export const OFFICIAL_PRIVACY_MODEL_REVISION = PINNED_PRIVACY_MODEL_REVISION;

// SHA-256 values published as LFS object IDs by the pinned Hugging Face revision.
export const OFFICIAL_PRIVACY_Q4_ONNX_SHA256 = PINNED_PRIVACY_Q4_ONNX_SHA256;
export const OFFICIAL_PRIVACY_Q4_ONNX_SIZE = PINNED_PRIVACY_Q4_ONNX_SIZE;
export const OFFICIAL_PRIVACY_Q4_DATA_SHA256 = PINNED_PRIVACY_Q4_DATA_SHA256;
export const OFFICIAL_PRIVACY_Q4_DATA_SIZE = PINNED_PRIVACY_Q4_DATA_SIZE;
export const OFFICIAL_PRIVACY_TOKENIZER_SHA256 =
  PINNED_PRIVACY_TOKENIZER_SHA256;
export const OFFICIAL_PRIVACY_CALIBRATION_SHA256 =
  PINNED_PRIVACY_CALIBRATION_SHA256;

// SHA-256 of the ordered ONNX and external-data digests above.
export const OFFICIAL_PRIVACY_ARTIFACT_SHA256 = PINNED_PRIVACY_ARTIFACT_SHA256;
export const PRIVACY_DECODER_SHA256 = PINNED_PRIVACY_DECODER_SHA256;
export const DETERMINISTIC_DETECTOR_VERSION =
  PINNED_PRIVACY_DETERMINISTIC_DETECTOR_VERSION;

export const PRIVACY_CLASSIFIER_HASH = PINNED_PRIVACY_CLASSIFIER_HASH;
